### ISSUE TITLE
Rename "island" to "group"

### ISSUE THREAD

**Issue by Frando** [arso-project/sonar#33]
I propose to rename "island" to "group", everywhere (code, docs, routes). If we want to keep "island" in user-facing parts (cli, ui) that can be considered afterwards.

In the current efforts to make parts of sonar more generic, the "island" term is hurting, while "group" I think is a good term that covers both the technical model (a group of feeds) and in many cases the social model (a group of people exchanging information, also people are quite familiar with the term group from messenger groups). It fits very well to cabal, its what cobox uses internally (in the user-facing UI they use "space").

Please voice objections soon, I'd like to do the change in the next days.

**Comment by Frando** [comment]
See #34

**Comment by hng** [comment]
We've decided to keep the island metaphor.
